version: '3.9'

services:
  backend:
    build: ./car-rental-backend
    container_name: car_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - carnet

  frontend:
    build: ./car-rental-frontend
    container_name: car_frontend
    ports:
      - "3000:80"
    networks:
      - carnet
    depends_on:
      - backend

networks:
  carnet:
    driver: bridge
